openapi: 3.0.0
info:
  title: Simple Apollo GraphQL Server
  version: 1.0.0
paths:
  /graphql:
    post:
      summary: Execute GraphQL queries
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                variables:
                  type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object

